const all_products = [

    {
        "name": "SHOES",
        "price": 5,
        "imgUrl": "https://images.pexels.com/photos/1464625/pexels-photo-1464625.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=740",
        "info": "Lorem ipsum dolor sit amet consectetur.",
        "badge": "-10%",
        "title": "Comfortable Footwear",
        "quantity": 1, 
        "rating": 4.2, 
    },
    {
        "name": "MEN's T-SHIRT",
        "price": 6.34,
        "imgUrl": "https://images.pexels.com/photos/3649765/pexels-photo-3649765.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "info": "Lorem ipsum dolor sit.",
        "badge": "-20%",
        "title": "Casual Men's Tee",
        "quantity": 1,
        "rating": 4.0,
    },
    {
        "name": "JEANS",
        "price": 9,
        "imgUrl": "https://www.realmenrealstyle.com/wp-content/uploads/2021/07/mens-jeans.jpg",
        "info": "Lorem ipsum dolor sit amet.",
        "badge": "-15%",
        "title": "Classic Blue Jeans",
        "quantity": 1,
        "rating": 4.5,
    },
    {
        "name": "WATCH",
        "price": 9.1,
        "imgUrl": "https://images.pexels.com/photos/8839887/pexels-photo-8839887.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "info": "Lorem ipsum dolor sit.",
        "badge": "-5%",
        "title": "Elegant Wristwatch",
        "quantity": 1,
        "rating": 4.7,
    },
    {
        "name": "SMART PHONE",
        "price": 20,
        "imgUrl": "https://images.pexels.com/photos/6858618/pexels-photo-6858618.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "info": "Lorem ipsum dolor sit.",
        "badge": "-12%",
        "title": "High-Performance Smartphone",
        "quantity": 1,
        "rating": 4.8,
    },
    {
        "name": "TELEVISION",
        "price": 18,
        "imgUrl": "https://images.pexels.com/photos/5552789/pexels-photo-5552789.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "info": "Lorem ipsum dolor sit amet consectetur.",
        "badge": "-8%",
        "title": "Ultra HD TV",
        "quantity": 1,
        "rating": 4.6,
    },
    {
        "name": "HOODIES",
        "price": 6.7,
        "imgUrl": "https://images.pexels.com/photos/4295985/pexels-photo-4295985.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "info": "Lorem ipsum dolor sit.",
        "badge": "-18%",
        "title": "Cozy Hooded Sweatshirt",
        "quantity": 1,
        "rating": 4.3,
    },
    {
        "name": "BLANKETS",
        "price": 9.9,
        "imgUrl": "https://images.pexels.com/photos/6463348/pexels-photo-6463348.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "info": "Lorem ipsum dolor sit amet consectetur adipisicing.",
        "badge": "-10%",
        "title": "Warm and Soft Blanket",
        "quantity": 1,
        "rating": 4.4,
    },
    {
        "name": "LAPTOP",
        "price": 99,
        "imgUrl": "https://images.pexels.com/photos/2659939/pexels-photo-2659939.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "info": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "badge": "-15%",
        "title": "High-Performance Laptop",
        "quantity": 1,
        "rating": 4.7,
    },
    {
        "name": "WASHING MACHINE",
        "price": 56,
        "imgUrl": "https://images.pexels.com/photos/5816934/pexels-photo-5816934.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "info": "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
        "badge": "-10%",
        "title": "Efficient Washing Machine",
        "quantity": 1,
        "rating": 4.5,
    }
];

module.exports = all_products;
